version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fm.auth:0.0.1
    restart: unless-stopped
    tty: true
    env_file: .env.example
    ports:
      - "8000:6001"
    networks:
      - bridge
    working_dir: /root

networks:
  bridge:
    driver: bridge
